name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: PoliNetworkBot_CSharp
    - name: Publish
      run: |
        dotnet publish --no-restore -o dist
        TZ='Europe/Rome' date > build-date.txt
      working-directory: PoliNetworkBot_CSharp
      
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: PoliNetworkBot_CSharp
      
    - name: Git management
      run: |
        cd /home/runner/work/PoliNetworkBot_CSharp/PoliNetworkBot_CSharp/PoliNetworkBot_CSharp/dist/
        cp -r ../static/ ./static
        git init
        git remote add origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        git add  .
        git status
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Action"
        git commit -m "artifact"
        git switch -c release
        git push origin release -f


