name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: PoliNetworkBot_CSharp
    - name: Publish
      run: |
        dotnet publish --no-restore -o dist
        TZ='Europe/Rome' date > build-date.txt
      working-directory: PoliNetworkBot_CSharp
      
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: PoliNetworkBot_CSharp
      
    - name: Git management
      run: |
        cd dist
        git init
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add .

    - name: Configure git (1)
      run: git config --global user.email "actions@github.com"

    - name: Configure git (2)
      run: git config --global user.name "Github Action"

    - name: Git commit
      run: git commit -m "artifact" 
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: release
        force: true



