name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: PoliNetworkBot_CSharp
    - name: Build
      run: |
        dotnet build --no-restore
        TZ='Europe/Rome' date > build-date.txt
      working-directory: PoliNetworkBot_CSharp
      
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: PoliNetworkBot_CSharp
      
    - name: Git management
      run: |
        git stash
        git switch --orphan release
        git stash show -p | git apply && git stash drop
        git add */bin/*  --ignore-errors  
        git add *.dll  --ignore-errors  


    - name: Configure git (1)
      run: git config --global user.email "actions@github.com"

    - name: Configure git (2)
      run: git config --global user.name "Github Action"

    - name: Git commit
      run: git commit -m "artifact" 
 
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BUILDTOKEN }}
        branch: release
        force: true



